# Generated by Django 2.0.7 on 2018-07-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('key_1', models.CharField(max_length=200)),
                ('key_2', models.CharField(max_length=200)),
                ('key_3', models.CharField(max_length=200)),
            ],
        ),
    ]
